--- 
services: 
  database: 
    image: mysql:5.7
    environment: 
      MYSQL_DATABASE: booklender
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root   
    ports: 
      - "8011:3306"
    restart: always
    volumes: 
      - container-volume:/var/lib/mysql
      - ./query.sql:/docker-entrypoint-initdb.d/query.sql
  javaserver: 
    build: 
      context: "."
    depends_on: 
      - database
    ports: 
      - "8010:8080"
    restart: always
version: "3.7"
volumes: 
  container-volume:
